// Code generated by github.com/tizz98/results; DO NOT EDIT.
package results

import (
	"context"
	"fmt"
)

type Int16Result struct {
	value *int16
	err   error
}

// SetNewInt16Result is a shortcut to creating a new Int16Result and then calling .Set(v, err) on it.
func SetNewInt16Result(v int16, err error) (result Int16Result) {
	result.Set(v, err)
	return
}

// SetNewInt16ResultPtr is a shortcut to creating a new Int16Result and then calling .Set(v, err) on it.
// This function differs from SetNewInt16Result by returning a pointer to Int16Result.
func SetNewInt16ResultPtr(v int16, err error) *Int16Result {
	result := SetNewInt16Result(v, err)
	return &result
}

// NewOptionalInt16Result is a shortcut to creating a new Int16Result and then calling .SetOptional(v, err) on it.
func NewOptionalInt16Result(v *int16, err error) (result Int16Result) {
	result.SetOptional(v, err)
	return
}

// NewOptionalInt16ResultPtr is a shortcut to creating a new Int16Result and then calling .SetOptional(v, err) on it.
// This function differs from NewOptionalInt16Result by returning a pointer to Int16Result.
func NewOptionalInt16ResultPtr(v *int16, err error) *Int16Result {
	result := NewOptionalInt16Result(v, err)
	return &result
}

// IsOk returns true when the result contains a non-nil result with no error
func (r Int16Result) IsOk() bool {
	return r.err == nil
}

// IsErr returns true when the result contains a non-nil error
func (r Int16Result) IsErr() bool {
	return r.err != nil
}

// Unwrap panics if the result contains an error, otherwise it returns the value
func (r Int16Result) Unwrap() int16 {
	if r.IsErr() {
		panic("cannot unwrap Int16Result, it is an error")
	}
	return *r.value
}

// UnwrapTo will call the .Err() method on the other Result if this Int16Result has an error.
// If other is a pointer to a Int16Result, then .Ok() will be called if this Int16Result name does not have an error.
func (r Int16Result) UnwrapTo(other Result) Result {
	if r.IsErr() {
		other.Err(r.GetErr())
	} else if other, ok := other.(*Int16Result); ok {
		other.Ok(r.Unwrap())
	}

	return other
}

// Expect panics with the specified message if the result contains an error, otherwise it returns the value
func (r Int16Result) Expect(message string) int16 {
	if r.IsErr() {
		panic(fmt.Errorf("%s: %w", message, r.GetErr()))
	}
	return *r.value
}

// Expectf panics with the specified message if the result contains an error, otherwise it returns the value.
// This is different than Expect because if will automatically format the string with the given args.
func (r Int16Result) Expectf(format string, args ...interface{}) int16 {
	if r.IsErr() {
		panic(fmt.Errorf("%s: %w", fmt.Sprintf(format, args...), r.GetErr()))
	}
	return *r.value
}

// UnwrapOr returns the value if there is not an error, otherwise the specified value is returned
func (r Int16Result) UnwrapOr(v int16) int16 {
	if r.IsOk() {
		return r.Unwrap()
	}
	return v
}

// UnwrapOrElse returns the value if there is not an error, otherwise the function is called and the result is returned
func (r Int16Result) UnwrapOrElse(fn func(err error) int16) int16 {
	if r.IsOk() {
		return r.Unwrap()
	}
	return fn(r.err)
}

// Ok sets the result to a successful result with the provided value.
// This will panic if the result has already been set to successful or an error.
func (r *Int16Result) Ok(v int16) {
	r.clear()
	r.value = &v
}

// Err sets the result to an error result with the provided error.
// This will panic if the result has already been set to successful or an error.
func (r *Int16Result) Err(err error) {
	r.clear()
	r.err = err
}

// GetError returns the error of the result. It may be nil, so check with Int16Result.IsErr() first.
func (r Int16Result) GetErr() error {
	return r.err
}

// Tup returns a tuple of (int16, error) with 0 being returned for int16 if there is an error
func (r Int16Result) Tup() (int16, error) {
	return r.UnwrapOr(0), r.err
}

// Set is a shortcut to checking the value of an error before setting the result.
// If there is an error, Int16Result.Err(err) will be called, otherwise Int16Result.Ok(v) will be called.
func (r *Int16Result) Set(v int16, err error) {
	if err != nil {
		r.Err(err)
	} else {
		r.Ok(v)
	}
}

// SetOptional is similar to Set but can be called with a nil value for int16.
// The error will be checked first to see if it is not nil, then if v is not nil it will be set with .Ok(v).
func (r *Int16Result) SetOptional(v *int16, err error) {
	if err != nil {
		r.Err(err)
	} else if v != nil {
		r.Ok(*v)
	}
}

// Ptr returns a pointer to the Int16Result
func (r Int16Result) Ptr() *Int16Result { return &r }

func (r Int16Result) clear() {
	r.value = nil
	r.err = nil
}

// ResultToInt16Result takes a Result interface and returns a Int16Result. If "r" contains a Int16Result,
// it is returned, otherwise a new Int16Result is returned with an error set.
func ResultToInt16Result(r Result) (result Int16Result) {
	v, ok := r.(*Int16Result)
	if !ok {
		result.Err(fmt.Errorf("expected *Int16Result got %T", v))
		return
	}

	return *v
}

// ContextWithInt16 embeds the given value of int16 into the context for later retrieval with Int16FromContext
func ContextWithInt16(ctx context.Context, key interface{}, v int16) context.Context {
	return context.WithValue(ctx, key, v)
}

// Int16FromContext attempts to retrieve a int16 value from the specified context. A Int16Result is returned
// which can be used to inspect the success or failure of retrieval.
func Int16FromContext(ctx context.Context, key interface{}) (result Int16Result) {
	if v, ok := ctx.Value(key).(int16); !ok {
		result.Err(fmt.Errorf("%#v not found in context", key))
	} else {
		result.Ok(v)
	}
	return
}
