// Code generated by github.com/tizz98/results; DO NOT EDIT.
package results

type Int8Result struct {
	value *int8
	err   error
}

// IsOk returns true when the result contains a non-nil result with no error
func (r Int8Result) IsOk() bool {
	return r.err == nil
}

// IsErr returns true when the result contains a non-nil error
func (r Int8Result) IsErr() bool {
	return r.err != nil
}

// Unwrap panics if the result contains an error, otherwise it returns the value
func (r Int8Result) Unwrap() int8 {
	if r.IsErr() {
		panic("cannot unwrap Int8Result, it is an error")
	}
	return *r.value
}

// UnwrapOr returns the value if there is not an error, otherwise the specified value is returned
func (r Int8Result) UnwrapOr(v int8) int8 {
	if r.IsOk() {
		return r.Unwrap()
	}
	return v
}

// UnwrapOrElse returns the value if there is not an error, otherwise the function is called and the result is returned
func (r Int8Result) UnwrapOrElse(fn func(err error) int8) int8 {
	if r.IsOk() {
		return r.Unwrap()
	}
	return fn(r.err)
}

// Ok sets the result to a successful result with the provided value.
// This will panic if the result has already been set to successful or an error.
func (r *Int8Result) Ok(v int8) {
	r.checkAbilityToSet()
	r.value = &v
}

// Err sets the result to an error result with the provided error.
// This will panic if the result has already been set to successful or an error.
func (r *Int8Result) Err(err error) {
	r.checkAbilityToSet()
	r.err = err
}

// GetError returns the error of the result. It may be nil, so check with Int8Result.IsErr() first.
func (r Int8Result) GetErr() error {
	return r.err
}

// Tup returns a tuple of (int8, error) with 0 being returned for int8 if there is an error
func (r Int8Result) Tup() (int8, error) {
	return r.UnwrapOr(0), r.err
}

// Set is a shortcut to checking the value of an error before setting the result.
// If there is an error, Int8Result.Err(err) will be called, otherwise Int8Result.Ok(v) will be called.
func (r *Int8Result) Set(v int8, err error) {
	if err != nil {
		r.Err(err)
		return
	}

	r.Ok(v)
}

func (r Int8Result) checkAbilityToSet() {
	if r.isSet() {
		panic("Int8Result is already set, cannot set again")
	}
}

func (r Int8Result) isSet() bool {
	return r.value != nil || r.err != nil
}
