// Code generated by github.com/tizz98/results; DO NOT EDIT.
package results

import (
	"context"
	"fmt"
)

type UintResult struct {
	value *uint
	err   error
}

// SetNewUintResult is a shortcut to creating a new UintResult and then calling .Set(v, err) on it.
func SetNewUintResult(v uint, err error) (result UintResult) {
	result.Set(v, err)
	return
}

// SetNewUintResultPtr is a shortcut to creating a new UintResult and then calling .Set(v, err) on it.
// This function differs from SetNewUintResult by returning a pointer to UintResult.
func SetNewUintResultPtr(v uint, err error) *UintResult {
	result := SetNewUintResult(v, err)
	return &result
}

// NewOptionalUintResult is a shortcut to creating a new UintResult and then calling .SetOptional(v, err) on it.
func NewOptionalUintResult(v *uint, err error) (result UintResult) {
	result.SetOptional(v, err)
	return
}

// NewOptionalUintResultPtr is a shortcut to creating a new UintResult and then calling .SetOptional(v, err) on it.
// This function differs from NewOptionalUintResult by returning a pointer to UintResult.
func NewOptionalUintResultPtr(v *uint, err error) *UintResult {
	result := NewOptionalUintResult(v, err)
	return &result
}

// IsOk returns true when the result contains a non-nil result with no error
func (r UintResult) IsOk() bool {
	return r.err == nil
}

// IsErr returns true when the result contains a non-nil error
func (r UintResult) IsErr() bool {
	return r.err != nil
}

// Unwrap panics if the result contains an error, otherwise it returns the value
func (r UintResult) Unwrap() uint {
	if r.IsErr() {
		panic("cannot unwrap UintResult, it is an error")
	}
	return *r.value
}

// UnwrapTo will call the .Err() method on the other Result if this UintResult has an error.
// If other is a pointer to a UintResult, then .Ok() will be called if this UintResult name does not have an error.
func (r UintResult) UnwrapTo(other Result) Result {
	if r.IsErr() {
		other.Err(r.GetErr())
	} else if other, ok := other.(*UintResult); ok {
		other.Ok(r.Unwrap())
	}

	return other
}

// Expect panics with the specified message if the result contains an error, otherwise it returns the value
func (r UintResult) Expect(message string) uint {
	if r.IsErr() {
		panic(fmt.Errorf("%s: %w", message, r.GetErr()))
	}
	return *r.value
}

// Expectf panics with the specified message if the result contains an error, otherwise it returns the value.
// This is different than Expect because if will automatically format the string with the given args.
func (r UintResult) Expectf(format string, args ...interface{}) uint {
	if r.IsErr() {
		panic(fmt.Errorf("%s: %w", fmt.Sprintf(format, args...), r.GetErr()))
	}
	return *r.value
}

// UnwrapOr returns the value if there is not an error, otherwise the specified value is returned
func (r UintResult) UnwrapOr(v uint) uint {
	if r.IsOk() {
		return r.Unwrap()
	}
	return v
}

// UnwrapOrElse returns the value if there is not an error, otherwise the function is called and the result is returned
func (r UintResult) UnwrapOrElse(fn func(err error) uint) uint {
	if r.IsOk() {
		return r.Unwrap()
	}
	return fn(r.err)
}

// Ok sets the result to a successful result with the provided value.
// This will panic if the result has already been set to successful or an error.
func (r *UintResult) Ok(v uint) {
	r.clear()
	r.value = &v
}

// Err sets the result to an error result with the provided error.
// This will panic if the result has already been set to successful or an error.
func (r *UintResult) Err(err error) {
	r.clear()
	r.err = err
}

// GetError returns the error of the result. It may be nil, so check with UintResult.IsErr() first.
func (r UintResult) GetErr() error {
	return r.err
}

// Tup returns a tuple of (uint, error) with 0 being returned for uint if there is an error
func (r UintResult) Tup() (uint, error) {
	return r.UnwrapOr(0), r.err
}

// Set is a shortcut to checking the value of an error before setting the result.
// If there is an error, UintResult.Err(err) will be called, otherwise UintResult.Ok(v) will be called.
func (r *UintResult) Set(v uint, err error) {
	if err != nil {
		r.Err(err)
	} else {
		r.Ok(v)
	}
}

// SetOptional is similar to Set but can be called with a nil value for uint.
// The error will be checked first to see if it is not nil, then if v is not nil it will be set with .Ok(v).
func (r *UintResult) SetOptional(v *uint, err error) {
	if err != nil {
		r.Err(err)
	} else if v != nil {
		r.Ok(*v)
	}
}

// Ptr returns a pointer to the UintResult
func (r UintResult) Ptr() *UintResult { return &r }

func (r UintResult) clear() {
	r.value = nil
	r.err = nil
}

// ResultToUintResult takes a Result interface and returns a UintResult. If "r" contains a UintResult,
// it is returned, otherwise a new UintResult is returned with an error set.
func ResultToUintResult(r Result) (result UintResult) {
	v, ok := r.(*UintResult)
	if !ok {
		result.Err(fmt.Errorf("expected *UintResult got %T", v))
		return
	}

	return *v
}

// ContextWithUint embeds the given value of uint into the context for later retrieval with UintFromContext
func ContextWithUint(ctx context.Context, key interface{}, v uint) context.Context {
	return context.WithValue(ctx, key, v)
}

// UintFromContext attempts to retrieve a uint value from the specified context. A UintResult is returned
// which can be used to inspect the success or failure of retrieval.
func UintFromContext(ctx context.Context, key interface{}) (result UintResult) {
	if v, ok := ctx.Value(key).(uint); !ok {
		result.Err(fmt.Errorf("%#v not found in context", key))
	} else {
		result.Ok(v)
	}
	return
}
